# Generated by Django 4.2.25 on 2025-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
