# Generated by Django 4.2.25 on 2025-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_patientmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sent_to_patient',
            field=models.BooleanField(default=False),
        ),
    ]
